In [64]:
#!pip install selenium==4.2.0 --force-reinstall
#https://pythoninoffice.com/fixing-attributeerror-webdriver-object-has-no-attribute-find_element_by_xpath/

In [65]:
#!pip3 install selenium==4.2.0 --force-reinstall

In [1]:
import os
import time
import re
import json
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from collections import Counter as cnt

In [2]:

  
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from time import sleep
import os
import wget

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

import requests
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import json

import time
site= 'http://www.ciiagro.org.br/diario/periodo'


#browser = webdriver.Chrome("./chromedriver")

browser = webdriver.Chrome()

browser.get(site)

# no chrome
help

sobre google chrome

chrome://settings/help

#atualizou Versão 125.0.6422.141 (Versão oficial) 64 bits
Versão 126.0.6478.126 (Versão oficial) 64 bits

(base) nomedodono_Computador@ROOT:~/Documentos/CRIACAO-HD/NOTA-PYTHON-LIRA/Chrome_drive_versao$ sudo apt install google-chrome-stable



Chromedrive
https://developer.chrome.com/docs/chromedriver/downloads?hl=pt-br

https://googlechromelabs.github.io/chrome-for-testing/

https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip

(base) nomedodono_Computador@ROOT:/Documentos/CRIACAO-HD/NOTA-PYTHON-LIRA/Chrome_drive_versao/chromedriver-linux64: ls

chromedriver  LICENSE.chromedriver

(base) nomedodono_Computador@ROOT:/Documentos/CRIACAO-HD/NOTA-PYTHON-LIRA/Chrome_drive_versao/chromedriver-linux64: sudo cp chromedriver /usr/local/bin/

[sudo] senha para nomedodono_Computador:

In [3]:
ano_escrito='1992'
data1quero= '01/11/1992'
data2quero= '02/07/2024'

In [69]:
#pegar a data

In [5]:
time.sleep(5)

#full xpath
#campinas

#cajati
#submit = browser.find_element(By.XPATH,"/html/body/section/div[1]/div/div/div/div[1]/form/fieldset/div[1]/label[42]/input")

submit = browser.find_element(By.XPATH,"/html/body/section/div[1]/div/div/div/div[1]/form/fieldset/div[1]/label[44]/input")
time.sleep(5)
submit.click()

In [6]:
Dataescrita1 = browser.find_element(By.XPATH,'/html/body/section/div[1]/div/div/div/div[1]/form/fieldset/div[2]/input[1]').send_keys(data1quero)
Dataescrita2 = browser.find_element(By.XPATH,'/html/body/section/div[1]/div/div/div/div[1]/form/fieldset/div[2]/input[2]').send_keys(data2quero)

submit2 = browser.find_element(By.XPATH,'/html/body/section/div[1]/div/div/div/div[1]/form/fieldset/div[3]/div/button[1]')

time.sleep(7)
submit2.click()

In [7]:
import pandas as pd
import requests

In [8]:
from selenium.webdriver.common.by import By

In [11]:
time.sleep(7)

#element = browser.find_element_by_xpath("/html/body/section/div[1]/div/div/table[2]")
#alterado o caminho
#element = browser.find_element_by_xpath("/html/body/section/div[1]/div/div/table[2]")
#xpath
element = browser.find_element("xpath","/html/body/section/div[1]/div/div/table[2]")


html_content = element.get_attribute('outerHTML')

In [12]:
print(html_content)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [13]:
soup = BeautifulSoup(html_content, 'html.parser')
#table = soup.find(name='table')
table = soup.find_all('table')
df = pd.read_html(str(table))

/tmp/ipykernel_17126/3523326099.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))

In [14]:
display(df[0])

          Local        Data Temperatura (°C)                 \
          Local        Data           Mínima   Média Máxima
0      Campinas  01-11-1992            17.20  23.500  29.80
1      Campinas  02-11-1992            18.20  24.300  30.40
2      Campinas  03-11-1992            19.80  24.900  30.00
3      Campinas  04-11-1992            18.00  21.900  25.80
4      Campinas  05-11-1992            12.00  16.700  21.40
...         ...         ...              ...     ...    ...
11562  Campinas  28-06-2024            15.18  21.480  27.78
11563  Campinas  29-06-2024            15.10  21.315  27.53
11564  Campinas  30-06-2024            16.25  22.780  29.31
11565  Campinas  01-07-2024            12.54  18.020  23.50
11566  Campinas  02-07-2024            11.33  14.320  17.31

      Umidade do ar (mm)                Precipitação (mm)
                  Mínima   Média Máxima Precipitação (mm)
0                    NaN   0.000    NaN              0.00
1                    NaN   0.000    NaN             34.20
2                    NaN   0.000    NaN              0.00
3                    NaN   0.000    NaN             70.80
4                    NaN   0.000    NaN              4.80
...                  ...     ...    ...               ...
11562              59.55  79.775  100.0              0.00
11563              50.94  75.470  100.0              0.00
11564              43.23  70.915   98.6              0.00
11565              65.91  82.855   99.8              0.51
11566              77.32  88.660  100.0              0.00

[11567 rows x 9 columns]

In [15]:
Basedados = pd.DataFrame(df[0])

In [16]:
list(Basedados.columns)

[('Local', 'Local'),
 ('Data', 'Data'),
 ('Temperatura (°C)', 'Mínima'),
 ('Temperatura (°C)', 'Média'),
 ('Temperatura (°C)', 'Máxima'),
 ('Umidade do ar (mm)', 'Mínima'),
 ('Umidade do ar (mm)', 'Média'),
 ('Umidade do ar (mm)', 'Máxima'),
 ('Precipitação (mm)', 'Precipitação (mm)')]

In [17]:
Basedados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11567 entries, 0 to 11566
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   (Local, Local)                          11567 non-null  object
 1   (Data, Data)                            11567 non-null  object
 2   (Temperatura (°C), Mínima)              11567 non-null  float64
 3   (Temperatura (°C), Média)               11567 non-null  float64
 4   (Temperatura (°C), Máxima)              11567 non-null  float64
 5   (Umidade do ar (mm), Mínima)            4804 non-null   float64
 6   (Umidade do ar (mm), Média)             11567 non-null  float64
 7   (Umidade do ar (mm), Máxima)            4804 non-null   float64
 8   (Precipitação (mm), Precipitação (mm))  11567 non-null  float64
dtypes: float64(7), object(2)
memory usage: 813.4+ KB

In [18]:
Basedados["chuva (mm)"]=Basedados['Precipitação (mm)', 'Precipitação (mm)']

In [19]:
Basedados['tmin'] = Basedados['Temperatura (°C)', 'Mínima']

In [20]:
Basedados['tmax'] = Basedados['Temperatura (°C)', 'Máxima']

In [21]:
Basedados['cidade']  = Basedados['Local', 'Local']

In [22]:
Basedados['Data', 'Data'] = pd.to_datetime(Basedados['Data', 'Data'], dayfirst=True)

In [23]:
Basedados["Dia_tabela"] = (Basedados['Data', 'Data'].dt.day)
Basedados["Mes_tabela"] = (Basedados['Data', 'Data'].dt.month)
Basedados["Ano_tabela"] = Basedados['Data', 'Data'].dt.year

In [24]:
display(Basedados)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
0      Campinas 1992-11-01            17.20  23.500  29.80                NaN
1      Campinas 1992-11-02            18.20  24.300  30.40                NaN
2      Campinas 1992-11-03            19.80  24.900  30.00                NaN
3      Campinas 1992-11-04            18.00  21.900  25.80                NaN
4      Campinas 1992-11-05            12.00  16.700  21.40                NaN
...         ...        ...              ...     ...    ...                ...
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11564  Campinas 2024-06-30            16.25  22.780  29.31              43.23
11565  Campinas 2024-07-01            12.54  18.020  23.50              65.91
11566  Campinas 2024-07-02            11.33  14.320  17.31              77.32

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
0       0.000    NaN              0.00       0.00  17.20  29.80  Campinas
1       0.000    NaN             34.20      34.20  18.20  30.40  Campinas
2       0.000    NaN              0.00       0.00  19.80  30.00  Campinas
3       0.000    NaN             70.80      70.80  18.00  25.80  Campinas
4       0.000    NaN              4.80       4.80  12.00  21.40  Campinas
...       ...    ...               ...        ...    ...    ...       ...
11562  79.775  100.0              0.00       0.00  15.18  27.78  Campinas
11563  75.470  100.0              0.00       0.00  15.10  27.53  Campinas
11564  70.915   98.6              0.00       0.00  16.25  29.31  Campinas
11565  82.855   99.8              0.51       0.51  12.54  23.50  Campinas
11566  88.660  100.0              0.00       0.00  11.33  17.31  Campinas

      Dia_tabela Mes_tabela Ano_tabela

0              1         11       1992
1              2         11       1992
2              3         11       1992
3              4         11       1992
4              5         11       1992
...          ...        ...        ...
11562         28          6       2024
11563         29          6       2024
11564         30          6       2024
11565          1          7       2024
11566          2          7       2024

[11567 rows x 16 columns]

In [25]:
quero_mes = 6
mes_escrito ="Junho"

In [26]:
mes_separa = Basedados.loc[(Basedados["Mes_tabela"] == quero_mes)]

In [27]:
mes_separa

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
212    Campinas 1993-06-01            16.00  18.300  20.60                NaN
213    Campinas 1993-06-02            13.00  17.300  21.60                NaN
214    Campinas 1993-06-03            13.40  19.300  25.20                NaN
215    Campinas 1993-06-04            14.40  20.500  26.60                NaN
216    Campinas 1993-06-05            15.00  17.300  19.60                NaN
...         ...        ...              ...     ...    ...                ...
11560  Campinas 2024-06-26            14.97  21.180  27.39              62.07
11561  Campinas 2024-06-27            15.00  22.875  30.75              45.30
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11564  Campinas 2024-06-30            16.25  22.780  29.31              43.23

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
212     0.000    NaN               1.1        1.1  16.00  20.60  Campinas
213     0.000    NaN               0.0        0.0  13.00  21.60  Campinas
214     0.000    NaN               0.0        0.0  13.40  25.20  Campinas
215     0.000    NaN               0.0        0.0  14.40  26.60  Campinas
216     0.000    NaN               4.8        4.8  15.00  19.60  Campinas
...       ...    ...               ...        ...    ...    ...       ...
11560  81.035  100.0               0.0        0.0  14.97  27.39  Campinas
11561  72.650  100.0               0.0        0.0  15.00  30.75  Campinas
11562  79.775  100.0               0.0        0.0  15.18  27.78  Campinas
11563  75.470  100.0               0.0        0.0  15.10  27.53  Campinas
11564  70.915   98.6               0.0        0.0  16.25  29.31  Campinas

      Dia_tabela Mes_tabela Ano_tabela

212            1          6       1993
213            2          6       1993
214            3          6       1993
215            4          6       1993
216            5          6       1993
...          ...        ...        ...
11560         26          6       2024
11561         27          6       2024
11562         28          6       2024
11563         29          6       2024
11564         30          6       2024

[960 rows x 16 columns]

In [28]:
mes_separa.sort_values('tmax' , ascending= False).head(40)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
11561  Campinas 2024-06-27            15.00  22.875  30.75              45.30
11559  Campinas 2024-06-25            14.92  22.780  30.64              43.07
7889   Campinas 2014-06-08            14.39  22.505  30.62              28.71
7890   Campinas 2014-06-09            15.10  22.760  30.42              26.00
11555  Campinas 2024-06-21            14.08  22.245  30.41              30.50
11547  Campinas 2024-06-13            13.87  22.090  30.31              35.13
11558  Campinas 2024-06-24            14.39  22.215  30.04              42.45
9734   Campinas 2019-06-27            15.56  22.780  30.00              23.03
11180  Campinas 2023-06-12            13.81  21.900  29.99              40.75
9370   Campinas 2018-06-28            14.06  21.940  29.82              17.75
11550  Campinas 2024-06-16            15.06  22.435  29.81              43.61
597    Campinas 1994-06-21            13.40  21.600  29.80                NaN
11546  Campinas 2024-06-12            15.64  22.700  29.76              44.13
11542  Campinas 2024-06-08            14.94  22.345  29.75              44.76
9367   Campinas 2018-06-25            14.59  22.155  29.72              20.03
11181  Campinas 2023-06-13            13.81  21.745  29.68              41.29
1325   Campinas 1996-06-18            14.20  21.900  29.60                NaN
3137   Campinas 2001-06-04            16.40  23.000  29.60                NaN
7910   Campinas 2014-06-29            13.78  21.690  29.60              23.99
9353   Campinas 2018-06-11            15.34  22.465  29.59              38.12
9369   Campinas 2018-06-27            12.83  21.205  29.58              17.85
11557  Campinas 2024-06-23            14.15  21.855  29.56              39.17
11551  Campinas 2024-06-17            14.63  22.085  29.54              44.42
9736   Campinas 2019-06-29            14.61  22.075  29.54              28.04
11545  Campinas 2024-06-11            14.27  21.865  29.46              46.97
10827  Campinas 2022-06-24            12.38  20.910  29.44              34.46
10085  Campinas 2020-06-12            15.79  22.610  29.43              32.52
9355   Campinas 2018-06-13            18.25  23.840  29.43              36.22
11541  Campinas 2024-06-07            14.59  22.010  29.43              43.23
2793   Campinas 2000-06-25            10.00  19.700  29.40                NaN
3512   Campinas 2002-06-14            15.00  22.200  29.40                NaN
10086  Campinas 2020-06-13            16.20  22.795  29.39              29.51
11554  Campinas 2024-06-20            12.12  20.730  29.34              37.47
10443  Campinas 2021-06-05            14.66  21.995  29.33              23.11
11564  Campinas 2024-06-30            16.25  22.780  29.31              43.23
9354   Campinas 2018-06-12            16.05  22.665  29.28              36.99
10087  Campinas 2020-06-14            16.44  22.830  29.22              28.63
1332   Campinas 1996-06-25            16.40  22.800  29.20                NaN
2782   Campinas 2000-06-14            14.60  21.900  29.20                NaN
3870   Campinas 2003-06-07            16.80  23.000  29.20                NaN

                      Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média  Máxima Precipitação (mm)
11561  72.650  100.00             0.000      0.000  15.00  30.75  Campinas
11559  69.385   95.70             0.000      0.000  14.92  30.64  Campinas
7889   56.305   83.90             0.000      0.000  14.39  30.62  Campinas
7890   54.100   82.20             0.000      0.000  15.10  30.42  Campinas
11555  55.235   79.97             0.000      0.000  14.08  30.41  Campinas
11547  62.915   90.70             0.000      0.000  13.87  30.31  Campinas
11558  69.425   96.40             0.000      0.000  14.39  30.04  Campinas
9734   61.515  100.00             0.000      0.000  15.56  30.00  Campinas
11180  69.175   97.60             0.000      0.000  13.81  29.99  Campinas
9370   50.875   84.00             0.000      0.000  14.06  29.82  Campinas
11550  70.305   97.00             0.000      0.000  15.06  29.81  Campinas
597     0.000     NaN             0.000      0.000  13.40  29.80  Campinas
11546  70.265   96.40             0.000      0.000  15.64  29.76  Campinas
11542  68.730   92.70             0.000      0.000  14.94  29.75  Campinas
9367   47.800   75.57             0.000      0.000  14.59  29.72  Campinas
11181  69.545   97.80             0.000      0.000  13.81  29.68  Campinas
1325    0.000     NaN             0.000      0.000  14.20  29.60  Campinas
3137    0.000     NaN             0.000      0.000  16.40  29.60  Campinas
7910   55.745   87.50             0.000      0.000  13.78  29.60  Campinas
9353   64.460   90.80             0.000      0.000  15.34  29.59  Campinas
9369   46.860   75.87             0.000      0.000  12.83  29.58  Campinas
11557  67.085   95.00             0.000      0.000  14.15  29.56  Campinas
11551  69.510   94.60             0.000      0.000  14.63  29.54  Campinas
9736   60.920   93.80             0.000      0.000  14.61  29.54  Campinas
11545  73.485  100.00             0.000      0.000  14.27  29.46  Campinas
10827  64.730   95.00             0.000      0.000  12.38  29.44  Campinas
10085  66.210   99.90             0.000      0.000  15.79  29.43  Campinas
9355   64.260   92.30             4.064      4.064  18.25  29.43  Campinas
11541  70.165   97.10             0.000      0.000  14.59  29.43  Campinas
2793    0.000     NaN             0.000      0.000  10.00  29.40  Campinas
3512    0.000     NaN             0.000      0.000  15.00  29.40  Campinas
10086  62.855   96.20             0.000      0.000  16.20  29.39  Campinas
11554  66.835   96.20             0.000      0.000  12.12  29.34  Campinas
10443  61.555  100.00             0.000      0.000  14.66  29.33  Campinas
11564  70.915   98.60             0.000      0.000  16.25  29.31  Campinas
9354   63.195   89.40             0.000      0.000  16.05  29.28  Campinas
10087  55.215   81.80             0.000      0.000  16.44  29.22  Campinas
1332    0.000     NaN             0.000      0.000  16.40  29.20  Campinas
2782    0.000     NaN             0.000      0.000  14.60  29.20  Campinas
3870    0.000     NaN             0.000      0.000  16.80  29.20  Campinas

      Dia_tabela Mes_tabela Ano_tabela

11561         27          6       2024
11559         25          6       2024
7889           8          6       2014
7890           9          6       2014
11555         21          6       2024
11547         13          6       2024
11558         24          6       2024
9734          27          6       2019
11180         12          6       2023
9370          28          6       2018
11550         16          6       2024
597           21          6       1994
11546         12          6       2024
11542          8          6       2024
9367          25          6       2018
11181         13          6       2023
1325          18          6       1996
3137           4          6       2001
7910          29          6       2014
9353          11          6       2018
9369          27          6       2018
11557         23          6       2024
11551         17          6       2024
9736          29          6       2019
11545         11          6       2024
10827         24          6       2022
10085         12          6       2020
9355          13          6       2018
11541          7          6       2024
2793          25          6       2000
3512          14          6       2002
10086         13          6       2020
11554         20          6       2024
10443          5          6       2021
11564         30          6       2024
9354          12          6       2018
10087         14          6       2020
1332          25          6       1996
2782          14          6       2000
3870           7          6       2003

In [29]:
mes_separa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 960 entries, 212 to 11564
Data columns (total 16 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   (Local, Local)                          960 non-null    object
 1   (Data, Data)                            960 non-null    datetime64[ns]
 2   (Temperatura (°C), Mínima)              960 non-null    float64
 3   (Temperatura (°C), Média)               960 non-null    float64
 4   (Temperatura (°C), Máxima)              960 non-null    float64
 5   (Umidade do ar (mm), Mínima)            390 non-null    float64
 6   (Umidade do ar (mm), Média)             960 non-null    float64
 7   (Umidade do ar (mm), Máxima)            390 non-null    float64
 8   (Precipitação (mm), Precipitação (mm))  960 non-null    float64
 9   (chuva (mm), )                          960 non-null    float64
 10  (tmin, )                                960 non-null    float64
 11  (tmax, )                                960 non-null    float64
 12  (cidade, )                              960 non-null    object
 13  (Dia_tabela, )                          960 non-null    int32
 14  (Mes_tabela, )                          960 non-null    int32
 15  (Ano_tabela, )                          960 non-null    int32
dtypes: datetime64[ns](1), float64(10), int32(3), object(2)
memory usage: 116.2+ KB

In [30]:
Basedados.sort_values('tmax' , ascending= False).head(80)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
9201   Campinas 2018-01-10            19.42  43.165  66.91              55.93
10203  Campinas 2020-10-08            21.42  30.780  40.14              11.45
10202  Campinas 2020-10-07            23.43  31.170  38.91              14.24
11336  Campinas 2023-11-15            22.46  30.620  38.78              30.64
11287  Campinas 2023-09-27            23.19  30.975  38.76              35.55
...         ...        ...              ...     ...    ...                ...
7305   Campinas 2012-11-01            19.42  27.685  35.95              24.69
9817   Campinas 2019-09-18            19.23  27.580  35.93              13.80
8019   Campinas 2014-10-16            19.09  27.505  35.92              18.73
9843   Campinas 2019-10-14            21.90  28.910  35.92              15.12
8116   Campinas 2015-01-21            20.17  28.035  35.90              20.26

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
9201   71.865  87.80             0.000      0.000  19.42  66.91  Campinas
10203  43.760  76.07             0.000      0.000  21.42  40.14  Campinas
10202  35.235  56.23             0.000      0.000  23.43  38.91  Campinas
11336  64.470  98.30             0.510      0.510  22.46  38.78  Campinas
11287  65.375  95.20             0.000      0.000  23.19  38.76  Campinas
...       ...    ...               ...        ...    ...    ...       ...
7305   60.345  96.00             2.032      2.032  19.42  35.95  Campinas
9817   35.780  57.76             0.000      0.000  19.23  35.93  Campinas
8019   49.815  80.90             0.000      0.000  19.09  35.92  Campinas
9843   36.825  58.53             0.000      0.000  21.90  35.92  Campinas
8116   53.280  86.30             0.254      0.254  20.17  35.90  Campinas

      Dia_tabela Mes_tabela Ano_tabela

9201          10          1       2018
10203          8         10       2020
10202          7         10       2020
11336         15         11       2023
11287         27          9       2023
...          ...        ...        ...
7305           1         11       2012
9817          18          9       2019
8019          16         10       2014
9843          14         10       2019
8116          21          1       2015

[80 rows x 16 columns]

In [31]:
Menor_TMax_novembro = mes_separa.sort_values('tmax' , ascending= False).head(80)

In [32]:
display(Menor_TMax_novembro)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
11561  Campinas 2024-06-27            15.00  22.875  30.75              45.30
11559  Campinas 2024-06-25            14.92  22.780  30.64              43.07
7889   Campinas 2014-06-08            14.39  22.505  30.62              28.71
7890   Campinas 2014-06-09            15.10  22.760  30.42              26.00
11555  Campinas 2024-06-21            14.08  22.245  30.41              30.50
...         ...        ...              ...     ...    ...                ...
10442  Campinas 2021-06-04            13.47  21.075  28.68              22.94
10465  Campinas 2021-06-27            14.51  21.595  28.68              22.87
11537  Campinas 2024-06-03            12.91  20.765  28.62              42.32
8986   Campinas 2017-06-09            15.23  21.920  28.61              35.10
3135   Campinas 2001-06-02            16.00  22.300  28.60                NaN

                      Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média  Máxima Precipitação (mm)
11561  72.650  100.00              0.00       0.00  15.00  30.75  Campinas
11559  69.385   95.70              0.00       0.00  14.92  30.64  Campinas
7889   56.305   83.90              0.00       0.00  14.39  30.62  Campinas
7890   54.100   82.20              0.00       0.00  15.10  30.42  Campinas
11555  55.235   79.97              0.00       0.00  14.08  30.41  Campinas
...       ...     ...               ...        ...    ...    ...       ...
10442  61.470  100.00              0.00       0.00  13.47  28.68  Campinas
10465  61.435  100.00              0.00       0.00  14.51  28.68  Campinas
11537  69.110   95.90              0.00       0.00  12.91  28.62  Campinas
8986   62.950   90.80              2.54       2.54  15.23  28.61  Campinas
3135    0.000     NaN              0.00       0.00  16.00  28.60  Campinas

      Dia_tabela Mes_tabela Ano_tabela

11561         27          6       2024
11559         25          6       2024
7889           8          6       2014
7890           9          6       2014
11555         21          6       2024
...          ...        ...        ...
10442          4          6       2021
10465         27          6       2021
11537          3          6       2024
8986           9          6       2017
3135           2          6       2001

[80 rows x 16 columns]

In [33]:
Menor_TMin_novembro = mes_separa.sort_values('tmin' , ascending= True).head(40)

In [34]:
display(Menor_TMin_novembro)

          Local       Data Temperatura (°C)                  \
          Local       Data           Mínima    Média Máxima
602    Campinas 1994-06-26            0.300   7.1500  14.00
603    Campinas 1994-06-27            0.600   9.9000  19.20
604    Campinas 1994-06-28            2.000  12.6000  23.20
10468  Campinas 2021-06-30            2.491   9.1305  15.77
6813   Campinas 2011-06-28            3.737   9.8085  15.88
3154   Campinas 2001-06-21            4.000  10.6000  17.20
6814   Campinas 2011-06-29            4.044  11.7920  19.54
1680   Campinas 1997-06-08            4.200   9.9000  15.60
1681   Campinas 1997-06-09            4.400  11.9000  19.40
8625   Campinas 2016-06-13            5.181  11.3855  17.59
3160   Campinas 2001-06-27            5.200  10.9000  16.60
8624   Campinas 2016-06-12            5.244  12.1120  18.98
6058   Campinas 2009-06-03            5.400  12.0000  18.60
6059   Campinas 2009-06-04            5.800  14.7000  23.60
8623   Campinas 2016-06-11            5.994  12.5070  19.02
1682   Campinas 1997-06-10            6.000  14.2000  22.40
605    Campinas 1994-06-29            6.000  15.7000  25.40
8626   Campinas 2016-06-14            6.233  12.9815  19.73
5328   Campinas 2007-06-04            6.400  13.2000  20.00
3161   Campinas 2001-06-28            6.400  12.7000  19.00
6426   Campinas 2010-06-06            6.700  14.5500  22.40
8987   Campinas 2017-06-10            6.894  14.1920  21.49
6427   Campinas 2010-06-07            6.900  13.2000  19.50
8988   Campinas 2017-06-11            6.962  13.0610  19.16
6796   Campinas 2011-06-11            6.989  12.0495  17.11
8622   Campinas 2016-06-10            7.113  13.2665  19.42
6797   Campinas 2011-06-12            7.125  13.5275  19.93
11185  Campinas 2023-06-17            7.147  12.4235  17.70
5329   Campinas 2007-06-05            7.200  15.2000  23.20
5330   Campinas 2007-06-06            7.400  16.1000  24.80
6073   Campinas 2009-06-18            7.500  14.6500  21.80
6069   Campinas 2009-06-14            7.500  13.6000  19.70
6068   Campinas 2009-06-13            7.500  13.1000  18.70
11186  Campinas 2023-06-18            7.703  13.6015  19.50
6060   Campinas 2009-06-05            7.800  17.7000  27.60
6793   Campinas 2011-06-08            7.838  17.1290  26.42
6815   Campinas 2011-06-30            7.930  16.5250  25.12
6074   Campinas 2009-06-19            8.100  14.6500  21.20
6794   Campinas 2011-06-09            8.110  13.5600  19.01
8989   Campinas 2017-06-12            8.190  15.9300  23.67

      Umidade do ar (mm)                Precipitação (mm) chuva (mm)   tmin  \
                  Mínima   Média Máxima Precipitação (mm)
602                  NaN   0.000    NaN             7.800      7.800  0.300
603                  NaN   0.000    NaN             0.000      0.000  0.600
604                  NaN   0.000    NaN             0.000      0.000  2.000
10468              55.29  77.645  100.0             0.000      0.000  2.491
6813               46.43  70.065   93.7             0.762      0.762  3.737
3154                 NaN   0.000    NaN             0.600      0.600  4.000
6814               18.32  56.110   93.9             0.254      0.254  4.044
1680                 NaN   0.000    NaN             0.000      0.000  4.200
1681                 NaN   0.000    NaN             0.000      0.000  4.400
8625               22.26  57.530   92.8             0.000      0.000  5.181
3160                 NaN   0.000    NaN            16.100     16.100  5.200
8624               24.20  57.900   91.6             0.000      0.000  5.244
6058                 NaN   0.000    NaN             0.000      0.000  5.400
6059                 NaN   0.000    NaN             0.000      0.000  5.800
8623               32.71  61.905   91.1             0.000      0.000  5.994
1682                 NaN   0.000    NaN             0.000      0.000  6.000
605                  NaN   0.000    NaN             0.000      0.000  6.000
8626               18.41  49.405   80.4             0.000      0.000  6.233
5328                 NaN   0.000    NaN             0.700      0.700  6.400
3161                 NaN   0.000    NaN             0.000      0.000  6.400
6426                 NaN   0.000    NaN             0.300      0.300  6.700
8987               67.61  79.605   91.6             0.508      0.508  6.894
6427                 NaN   0.000    NaN             0.000      0.000  6.900
8988               27.62  59.610   91.6             0.000      0.000  6.962
6796               67.68  80.840   94.0             0.508      0.508  6.989
8622               32.40  63.750   95.1             0.000      0.000  7.113
6797               25.90  60.000   94.1             0.000      0.000  7.125
11185              83.60  91.800  100.0             0.250      0.250  7.147
5329                 NaN   0.000    NaN             0.000      0.000  7.200
5330                 NaN   0.000    NaN             0.000      0.000  7.400
6073                 NaN   0.000    NaN             0.000      0.000  7.500
6069                 NaN   0.000    NaN             0.000      0.000  7.500
6068                 NaN   0.000    NaN             1.000      1.000  7.500
11186              61.97  80.985  100.0             0.250      0.250  7.703
6060                 NaN   0.000    NaN             0.000      0.000  7.800
6793               38.07  65.485   92.9            21.840     21.840  7.838
6815               18.18  52.540   86.9             0.000      0.000  7.930
6074                 NaN   0.000    NaN             0.000      0.000  8.100
6794               41.54  67.320   93.1             0.254      0.254  8.110
8989               25.57  56.535   87.5             0.000      0.000  8.190

        tmax    cidade Dia_tabela Mes_tabela Ano_tabela

602    14.00  Campinas         26          6       1994
603    19.20  Campinas         27          6       1994
604    23.20  Campinas         28          6       1994
10468  15.77  Campinas         30          6       2021
6813   15.88  Campinas         28          6       2011
3154   17.20  Campinas         21          6       2001
6814   19.54  Campinas         29          6       2011
1680   15.60  Campinas          8          6       1997
1681   19.40  Campinas          9          6       1997
8625   17.59  Campinas         13          6       2016
3160   16.60  Campinas         27          6       2001
8624   18.98  Campinas         12          6       2016
6058   18.60  Campinas          3          6       2009
6059   23.60  Campinas          4          6       2009
8623   19.02  Campinas         11          6       2016
1682   22.40  Campinas         10          6       1997
605    25.40  Campinas         29          6       1994
8626   19.73  Campinas         14          6       2016
5328   20.00  Campinas          4          6       2007
3161   19.00  Campinas         28          6       2001
6426   22.40  Campinas          6          6       2010
8987   21.49  Campinas         10          6       2017
6427   19.50  Campinas          7          6       2010
8988   19.16  Campinas         11          6       2017
6796   17.11  Campinas         11          6       2011
8622   19.42  Campinas         10          6       2016
6797   19.93  Campinas         12          6       2011
11185  17.70  Campinas         17          6       2023
5329   23.20  Campinas          5          6       2007
5330   24.80  Campinas          6          6       2007
6073   21.80  Campinas         18          6       2009
6069   19.70  Campinas         14          6       2009
6068   18.70  Campinas         13          6       2009
11186  19.50  Campinas         18          6       2023
6060   27.60  Campinas          5          6       2009
6793   26.42  Campinas          8          6       2011
6815   25.12  Campinas         30          6       2011
6074   21.20  Campinas         19          6       2009
6794   19.01  Campinas          9          6       2011
8989   23.67  Campinas         12          6       2017

In [35]:
Menor_TMin_novembro.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 602 to 8989
Data columns (total 16 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   (Local, Local)                          40 non-null     object
 1   (Data, Data)                            40 non-null     datetime64[ns]
 2   (Temperatura (°C), Mínima)              40 non-null     float64
 3   (Temperatura (°C), Média)               40 non-null     float64
 4   (Temperatura (°C), Máxima)              40 non-null     float64
 5   (Umidade do ar (mm), Mínima)            18 non-null     float64
 6   (Umidade do ar (mm), Média)             40 non-null     float64
 7   (Umidade do ar (mm), Máxima)            18 non-null     float64
 8   (Precipitação (mm), Precipitação (mm))  40 non-null     float64
 9   (chuva (mm), )                          40 non-null     float64
 10  (tmin, )                                40 non-null     float64
 11  (tmax, )                                40 non-null     float64
 12  (cidade, )                              40 non-null     object
 13  (Dia_tabela, )                          40 non-null     int32
 14  (Mes_tabela, )                          40 non-null     int32
 15  (Ano_tabela, )                          40 non-null     int32
dtypes: datetime64[ns](1), float64(10), int32(3), object(2)
memory usage: 4.8+ KB

# Dados das menores temperaturas

In [36]:
Menor_TMin_novembro.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 602 to 8989
Data columns (total 16 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   (Local, Local)                          40 non-null     object
 1   (Data, Data)                            40 non-null     datetime64[ns]
 2   (Temperatura (°C), Mínima)              40 non-null     float64
 3   (Temperatura (°C), Média)               40 non-null     float64
 4   (Temperatura (°C), Máxima)              40 non-null     float64
 5   (Umidade do ar (mm), Mínima)            18 non-null     float64
 6   (Umidade do ar (mm), Média)             40 non-null     float64
 7   (Umidade do ar (mm), Máxima)            18 non-null     float64
 8   (Precipitação (mm), Precipitação (mm))  40 non-null     float64
 9   (chuva (mm), )                          40 non-null     float64
 10  (tmin, )                                40 non-null     float64
 11  (tmax, )                                40 non-null     float64
 12  (cidade, )                              40 non-null     object
 13  (Dia_tabela, )                          40 non-null     int32
 14  (Mes_tabela, )                          40 non-null     int32
 15  (Ano_tabela, )                          40 non-null     int32
dtypes: datetime64[ns](1), float64(10), int32(3), object(2)
memory usage: 4.8+ KB

In [37]:


for l, temperatura in enumerate(Menor_TMin_novembro['tmin']):
    print(temperatura)
    print(l)
    #print(Menor_TMin_novembro['Dia_tabela'][l])

0.3
0
0.6
1
2.0
2
2.491
3
3.737
4
4.0
5
4.044
6
4.2
7
4.4
8
5.181
9
5.2
10
5.244
11
5.4
12
5.8
13
5.994
14
6.0
15
6.0
16
6.233
17
6.4
18
6.4
19
6.7
20
6.894
21
6.9
22
6.962
23
6.989
24
7.113
25
7.125
26
7.147
27
7.2
28
7.4
29
7.5
30
7.5
31
7.5
32
7.703
33
7.8
34
7.838
35
7.93
36
8.1
37
8.11
38
8.19
39

In [66]:
print('Dados das menores temperaturas mínimas da história na cidade de {0} em um mês de {1}, dados desde {2}'.format('Campinas', mes_escrito,ano_escrito))
print('Fonte:Ciiagro')
print('=' * 40)
print('|{:^3}°)|{:^15}|{:^5}|{:^5}|{:^5}|'.format('Pos.','T. Min(°C)', 'Data','Mês', 'Ano'))
print('=' * 40)



conta = 0
for linha in Menor_TMin_novembro.index:
     #nome = tabela_produtos.loc[linha, coluna]
    Tmin = Menor_TMin_novembro.loc[linha, "tmin"]
    dia1 = int(Menor_TMin_novembro.loc[linha, "Dia_tabela"])   
    mes1 = int(Menor_TMin_novembro.loc[linha, "Mes_tabela"])
    ano1 = int(Menor_TMin_novembro.loc[linha,'Ano_tabela'] )
    Tmin2 = float(Tmin)
    temperatura1 = round(Tmin2,1)   
    
   # print(temperatura1)
    
    if temperatura1 < 5:
        print('|{:^3}°)|\033[42m{:^15}\033[0m|{:^5}|{:^5}|{:^5}|'.format(conta+1,temperatura1,dia1, mes1,ano1 ))

    else:
        print('|{:^3}°)|{:^15}|{:^5}|{:^5}|{:^5}|'.format(conta+1,temperatura1,dia1, mes1,ano1 ))
        
        pass
    conta = conta +1

print('=' * 40)

Dados das menores temperaturas mínimas da história na cidade de Campinas em um mês de Junho, dados desde 1992
Fonte:Ciiagro
========================================
|Pos.°)|  T. Min(°C)   |Data | Mês | Ano |
========================================
| 1 °)|      0.3      | 26  |  6  |1994 |
| 2 °)|      0.6      | 27  |  6  |1994 |
| 3 °)|      2.0      | 28  |  6  |1994 |
| 4 °)|      2.5      | 30  |  6  |2021 |
| 5 °)|      3.7      | 28  |  6  |2011 |
| 6 °)|      4.0      | 21  |  6  |2001 |
| 7 °)|      4.0      | 29  |  6  |2011 |
| 8 °)|      4.2      |  8  |  6  |1997 |
| 9 °)|      4.4      |  9  |  6  |1997 |
|10 °)|      5.2      | 13  |  6  |2016 |
|11 °)|      5.2      | 27  |  6  |2001 |
|12 °)|      5.2      | 12  |  6  |2016 |
|13 °)|      5.4      |  3  |  6  |2009 |
|14 °)|      5.8      |  4  |  6  |2009 |
|15 °)|      6.0      | 11  |  6  |2016 |
|16 °)|      6.0      | 10  |  6  |1997 |
|17 °)|      6.0      | 29  |  6  |1994 |

/tmp/ipykernel_17126/2335070189.py:13: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  dia1 = int(Menor_TMin_novembro.loc[linha, "Dia_tabela"])
/tmp/ipykernel_17126/2335070189.py:14: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  mes1 = int(Menor_TMin_novembro.loc[linha, "Mes_tabela"])
/tmp/ipykernel_17126/2335070189.py:15: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ano1 = int(Menor_TMin_novembro.loc[linha,'Ano_tabela'] )
/tmp/ipykernel_17126/2335070189.py:16: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Tmin2 = float(Tmin)

|18 °)|      6.2      | 14  |  6  |2016 |
|19 °)|      6.4      |  4  |  6  |2007 |
|20 °)|      6.4      | 28  |  6  |2001 |
|21 °)|      6.7      |  6  |  6  |2010 |
|22 °)|      6.9      | 10  |  6  |2017 |
|23 °)|      6.9      |  7  |  6  |2010 |
|24 °)|      7.0      | 11  |  6  |2017 |
|25 °)|      7.0      | 11  |  6  |2011 |
|26 °)|      7.1      | 10  |  6  |2016 |
|27 °)|      7.1      | 12  |  6  |2011 |
|28 °)|      7.1      | 17  |  6  |2023 |
|29 °)|      7.2      |  5  |  6  |2007 |
|30 °)|      7.4      |  6  |  6  |2007 |
|31 °)|      7.5      | 18  |  6  |2009 |
|32 °)|      7.5      | 14  |  6  |2009 |
|33 °)|      7.5      | 13  |  6  |2009 |
|34 °)|      7.7      | 18  |  6  |2023 |
|35 °)|      7.8      |  5  |  6  |2009 |
|36 °)|      7.8      |  8  |  6  |2011 |
|37 °)|      7.9      | 30  |  6  |2011 |
|38 °)|      8.1      | 19  |  6  |2009 |
|39 °)|      8.1      |  9  |  6  |2011 |
|40 °)|      8.2      | 12  |  6  |2017 |
========================================

In [67]:
print('Dados das MAIORES temperaturas máximas da história na cidade de {0} em um mês de {1}, dados desde {2}'.format('Campinas', mes_escrito, ano_escrito))
print('Fonte:Ciiagro')
print('=' * 40)
print('|{:^3}°)|{:^15}|{:^5}|{:^5}|{:^5}|'.format('Pos.','T. Máx(°C)', 'Data','Mês', 'Ano'))
print('=' * 40)



conta = 0
for linha in Menor_TMax_novembro.index:
     #nome = tabela_produtos.loc[linha, coluna]
    Tmin = Menor_TMax_novembro.loc[linha, "tmax"]
    dia1 = int(Menor_TMax_novembro.loc[linha, "Dia_tabela"])   
    mes1 = int(Menor_TMax_novembro.loc[linha, "Mes_tabela"])
    ano1 = int(Menor_TMax_novembro.loc[linha,'Ano_tabela'] )
    Tmin2 = float(Tmin)
    temperatura1 = round(Tmin2,1)   
    
   # print(temperatura1)
    
    if temperatura1 > 30:
        print('|{:^3}°)|\033[45m{:^15}\033[0m|{:^5}|{:^5}|{:^5}|'.format(conta+1,temperatura1,dia1-1, mes1,ano1 ))

    else:
        print('|{:^3}°)|{:^15}|{:^5}|{:^5}|{:^5}|'.format(conta+1,temperatura1,dia1-1, mes1,ano1 ))
        
        pass
    conta = conta +1

print('=' * 40)

Dados das MAIORES temperaturas máximas da história na cidade de Campinas em um mês de Junho, dados desde 1992
Fonte:Ciiagro
========================================
|Pos.°)|  T. Máx(°C)   |Data | Mês | Ano |
========================================
| 1 °)|     30.8      | 26  |  6  |2024 |
| 2 °)|     30.6      | 24  |  6  |2024 |
| 3 °)|     30.6      |  7  |  6  |2014 |
| 4 °)|     30.4      |  8  |  6  |2014 |
| 5 °)|     30.4      | 20  |  6  |2024 |
| 6 °)|     30.3      | 12  |  6  |2024 |
| 7 °)|     30.0      | 23  |  6  |2024 |
| 8 °)|     30.0      | 26  |  6  |2019 |
| 9 °)|     30.0      | 11  |  6  |2023 |
|10 °)|     29.8      | 27  |  6  |2018 |
|11 °)|     29.8      | 15  |  6  |2024 |
|12 °)|     29.8      | 20  |  6  |1994 |
|13 °)|     29.8      | 11  |  6  |2024 |
|14 °)|     29.8      |  7  |  6  |2024 |
|15 °)|     29.7      | 24  |  6  |2018 |
|16 °)|     29.7      | 12  |  6  |2023 |
|17 °)|     29.6      | 17  |  6  |1996 |
|18 °)|     29.6      |  3  |  6  |2001 |
|19 °)|     29.6      | 28  |  6  |2014 |
|20 °)|     29.6      | 10  |  6  |2018 |

/tmp/ipykernel_17126/1251659254.py:13: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  dia1 = int(Menor_TMax_novembro.loc[linha, "Dia_tabela"])
/tmp/ipykernel_17126/1251659254.py:14: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  mes1 = int(Menor_TMax_novembro.loc[linha, "Mes_tabela"])
/tmp/ipykernel_17126/1251659254.py:15: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ano1 = int(Menor_TMax_novembro.loc[linha,'Ano_tabela'] )
/tmp/ipykernel_17126/1251659254.py:16: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Tmin2 = float(Tmin)

|21 °)|     29.6      | 26  |  6  |2018 |
|22 °)|     29.6      | 22  |  6  |2024 |
|23 °)|     29.5      | 16  |  6  |2024 |
|24 °)|     29.5      | 28  |  6  |2019 |
|25 °)|     29.5      | 10  |  6  |2024 |
|26 °)|     29.4      | 23  |  6  |2022 |
|27 °)|     29.4      | 11  |  6  |2020 |
|28 °)|     29.4      | 12  |  6  |2018 |
|29 °)|     29.4      |  6  |  6  |2024 |
|30 °)|     29.4      | 24  |  6  |2000 |
|31 °)|     29.4      | 13  |  6  |2002 |
|32 °)|     29.4      | 12  |  6  |2020 |
|33 °)|     29.3      | 19  |  6  |2024 |
|34 °)|     29.3      |  4  |  6  |2021 |
|35 °)|     29.3      | 29  |  6  |2024 |
|36 °)|     29.3      | 11  |  6  |2018 |
|37 °)|     29.2      | 13  |  6  |2020 |
|38 °)|     29.2      | 24  |  6  |1996 |
|39 °)|     29.2      | 13  |  6  |2000 |
|40 °)|     29.2      |  6  |  6  |2003 |
|41 °)|     29.2      | 14  |  6  |2007 |
|42 °)|     29.2      | 27  |  6  |2000 |
|43 °)|     29.2      |  8  |  6  |2024 |
|44 °)|     29.2      | 24  |  6  |2022 |
|45 °)|     29.1      | 13  |  6  |2019 |
|46 °)|     29.1      | 27  |  6  |2014 |
|47 °)|     29.1      |  0  |  6  |2019 |
|48 °)|     29.1      | 14  |  6  |2024 |
|49 °)|     29.1      |  4  |  6  |2017 |
|50 °)|     29.1      |  9  |  6  |2024 |
|51 °)|     29.0      | 25  |  6  |2000 |
|52 °)|     29.0      | 11  |  6  |2002 |
|53 °)|     29.0      | 28  |  6  |2000 |
|54 °)|     29.0      | 17  |  6  |2007 |
|55 °)|     29.0      | 15  |  6  |2007 |
|56 °)|     29.0      | 14  |  6  |2019 |
|57 °)|     28.9      | 28  |  6  |2018 |
|58 °)|     28.9      | 25  |  6  |2021 |
|59 °)|     28.9      |  9  |  6  |2020 |
|60 °)|     28.8      | 25  |  6  |2019 |
|61 °)|     28.8      | 20  |  6  |2010 |
|62 °)|     28.8      | 16  |  6  |1996 |
|63 °)|     28.8      | 12  |  6  |2002 |
|64 °)|     28.8      |  8  |  6  |2007 |
|65 °)|     28.8      | 16  |  6  |2007 |
|66 °)|     28.8      | 25  |  6  |2018 |
|67 °)|     28.8      | 17  |  6  |2022 |
|68 °)|     28.8      | 10  |  6  |2020 |
|69 °)|     28.8      | 29  |  6  |2013 |
|70 °)|     28.8      |  5  |  6  |2014 |
|71 °)|     28.7      | 16  |  6  |2022 |
|72 °)|     28.7      | 18  |  6  |2024 |
|73 °)|     28.7      | 14  |  6  |2015 |
|74 °)|     28.7      | 25  |  6  |2020 |
|75 °)|     28.7      | 21  |  6  |2010 |
|76 °)|     28.7      |  3  |  6  |2021 |
|77 °)|     28.7      | 26  |  6  |2021 |
|78 °)|     28.6      |  2  |  6  |2024 |
|79 °)|     28.6      |  8  |  6  |2017 |
|80 °)|     28.6      |  1  |  6  |2001 |
========================================

In [41]:
print(f'final')

final

In [42]:
#doano2022 = oficial[oficial['Data Medicao'].between(f'2022-{data_1n}',f'2022-{data_2n}')]

In [43]:
Basedados.tail(10)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
11557  Campinas 2024-06-23            14.15  21.855  29.56              39.17
11558  Campinas 2024-06-24            14.39  22.215  30.04              42.45
11559  Campinas 2024-06-25            14.92  22.780  30.64              43.07
11560  Campinas 2024-06-26            14.97  21.180  27.39              62.07
11561  Campinas 2024-06-27            15.00  22.875  30.75              45.30
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11564  Campinas 2024-06-30            16.25  22.780  29.31              43.23
11565  Campinas 2024-07-01            12.54  18.020  23.50              65.91
11566  Campinas 2024-07-02            11.33  14.320  17.31              77.32

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
11557  67.085   95.0              0.00       0.00  14.15  29.56  Campinas
11558  69.425   96.4              0.00       0.00  14.39  30.04  Campinas
11559  69.385   95.7              0.00       0.00  14.92  30.64  Campinas
11560  81.035  100.0              0.00       0.00  14.97  27.39  Campinas
11561  72.650  100.0              0.00       0.00  15.00  30.75  Campinas
11562  79.775  100.0              0.00       0.00  15.18  27.78  Campinas
11563  75.470  100.0              0.00       0.00  15.10  27.53  Campinas
11564  70.915   98.6              0.00       0.00  16.25  29.31  Campinas
11565  82.855   99.8              0.51       0.51  12.54  23.50  Campinas
11566  88.660  100.0              0.00       0.00  11.33  17.31  Campinas

      Dia_tabela Mes_tabela Ano_tabela

11557         23          6       2024
11558         24          6       2024
11559         25          6       2024
11560         26          6       2024
11561         27          6       2024
11562         28          6       2024
11563         29          6       2024
11564         30          6       2024
11565          1          7       2024
11566          2          7       2024

In [44]:
#inicio da primavera

dataa= 21
mes_separa_inicioprimavera = Basedados.loc[(Basedados["Mes_tabela"] == quero_mes) & (Basedados["Dia_tabela"] > dataa) ]

In [45]:
mes_separa_inicioprimavera

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
233    Campinas 1993-06-22             8.60  17.200  25.80                NaN
234    Campinas 1993-06-23            10.40  17.900  25.40                NaN
235    Campinas 1993-06-24            10.80  18.100  25.40                NaN
236    Campinas 1993-06-25            11.80  18.700  25.60                NaN
237    Campinas 1993-06-26            12.00  18.900  25.80                NaN
...         ...        ...              ...     ...    ...                ...
11560  Campinas 2024-06-26            14.97  21.180  27.39              62.07
11561  Campinas 2024-06-27            15.00  22.875  30.75              45.30
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11564  Campinas 2024-06-30            16.25  22.780  29.31              43.23

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
233     0.000    NaN               0.0        0.0   8.60  25.80  Campinas
234     0.000    NaN               0.0        0.0  10.40  25.40  Campinas
235     0.000    NaN               0.0        0.0  10.80  25.40  Campinas
236     0.000    NaN               0.0        0.0  11.80  25.60  Campinas
237     0.000    NaN               0.0        0.0  12.00  25.80  Campinas
...       ...    ...               ...        ...    ...    ...       ...
11560  81.035  100.0               0.0        0.0  14.97  27.39  Campinas
11561  72.650  100.0               0.0        0.0  15.00  30.75  Campinas
11562  79.775  100.0               0.0        0.0  15.18  27.78  Campinas
11563  75.470  100.0               0.0        0.0  15.10  27.53  Campinas
11564  70.915   98.6               0.0        0.0  16.25  29.31  Campinas

      Dia_tabela Mes_tabela Ano_tabela

233           22          6       1993
234           23          6       1993
235           24          6       1993
236           25          6       1993
237           26          6       1993
...          ...        ...        ...
11560         26          6       2024
11561         27          6       2024
11562         28          6       2024
11563         29          6       2024
11564         30          6       2024

[288 rows x 16 columns]

In [46]:
Tmininicioprimavera = mes_separa_inicioprimavera.sort_values('tmin' , ascending= True).head(25)

In [47]:
Tmininicioprimavera

          Local       Data Temperatura (°C)                  \
          Local       Data           Mínima    Média Máxima
602    Campinas 1994-06-26            0.300   7.1500  14.00
603    Campinas 1994-06-27            0.600   9.9000  19.20
604    Campinas 1994-06-28            2.000  12.6000  23.20
10468  Campinas 2021-06-30            2.491   9.1305  15.77
6813   Campinas 2011-06-28            3.737   9.8085  15.88
6814   Campinas 2011-06-29            4.044  11.7920  19.54
3160   Campinas 2001-06-27            5.200  10.9000  16.60
605    Campinas 1994-06-29            6.000  15.7000  25.40
3161   Campinas 2001-06-28            6.400  12.7000  19.00
6815   Campinas 2011-06-30            7.930  16.5250  25.12
2792   Campinas 2000-06-24            8.200  16.9000  25.60
2791   Campinas 2000-06-23            8.200  16.9000  25.60
2790   Campinas 2000-06-22            8.200  15.6000  23.00
3156   Campinas 2001-06-23            8.400  16.9000  25.40
233    Campinas 1993-06-22            8.600  17.2000  25.80
1337   Campinas 1996-06-30            8.600  13.6000  18.60
2426   Campinas 1999-06-24            8.800  16.6000  24.40
6078   Campinas 2009-06-23            8.900  17.1000  25.30
606    Campinas 1994-06-30            9.000  17.9000  26.80
2424   Campinas 1999-06-22            9.000  14.2000  19.40
2432   Campinas 1999-06-30            9.000  16.0000  23.00
2427   Campinas 1999-06-25            9.000  17.4000  25.80
6077   Campinas 2009-06-22            9.100  17.3000  25.50
1336   Campinas 1996-06-29            9.200  11.9000  14.60
2425   Campinas 1999-06-23            9.400  15.8000  22.20

      Umidade do ar (mm)                Precipitação (mm) chuva (mm)   tmin  \
                  Mínima   Média Máxima Precipitação (mm)
602                  NaN   0.000    NaN             7.800      7.800  0.300
603                  NaN   0.000    NaN             0.000      0.000  0.600
604                  NaN   0.000    NaN             0.000      0.000  2.000
10468              55.29  77.645  100.0             0.000      0.000  2.491
6813               46.43  70.065   93.7             0.762      0.762  3.737
6814               18.32  56.110   93.9             0.254      0.254  4.044
3160                 NaN   0.000    NaN            16.100     16.100  5.200
605                  NaN   0.000    NaN             0.000      0.000  6.000
3161                 NaN   0.000    NaN             0.000      0.000  6.400
6815               18.18  52.540   86.9             0.000      0.000  7.930
2792                 NaN   0.000    NaN             0.000      0.000  8.200
2791                 NaN   0.000    NaN             0.000      0.000  8.200
2790                 NaN   0.000    NaN             0.000      0.000  8.200
3156                 NaN   0.000    NaN             0.000      0.000  8.400
233                  NaN   0.000    NaN             0.000      0.000  8.600
1337                 NaN   0.000    NaN             0.000      0.000  8.600
2426                 NaN   0.000    NaN             0.000      0.000  8.800
6078                 NaN   0.000    NaN             0.000      0.000  8.900
606                  NaN   0.000    NaN             0.000      0.000  9.000
2424                 NaN   0.000    NaN             0.000      0.000  9.000
2432                 NaN   0.000    NaN             1.200      1.200  9.000
2427                 NaN   0.000    NaN             0.000      0.000  9.000
6077                 NaN   0.000    NaN             0.000      0.000  9.100
1336                 NaN   0.000    NaN            15.100     15.100  9.200
2425                 NaN   0.000    NaN             0.000      0.000  9.400

        tmax    cidade Dia_tabela Mes_tabela Ano_tabela

602    14.00  Campinas         26          6       1994
603    19.20  Campinas         27          6       1994
604    23.20  Campinas         28          6       1994
10468  15.77  Campinas         30          6       2021
6813   15.88  Campinas         28          6       2011
6814   19.54  Campinas         29          6       2011
3160   16.60  Campinas         27          6       2001
605    25.40  Campinas         29          6       1994
3161   19.00  Campinas         28          6       2001
6815   25.12  Campinas         30          6       2011
2792   25.60  Campinas         24          6       2000
2791   25.60  Campinas         23          6       2000
2790   23.00  Campinas         22          6       2000
3156   25.40  Campinas         23          6       2001
233    25.80  Campinas         22          6       1993
1337   18.60  Campinas         30          6       1996
2426   24.40  Campinas         24          6       1999
6078   25.30  Campinas         23          6       2009
606    26.80  Campinas         30          6       1994
2424   19.40  Campinas         22          6       1999
2432   23.00  Campinas         30          6       1999
2427   25.80  Campinas         25          6       1999
6077   25.50  Campinas         22          6       2009
1336   14.60  Campinas         29          6       1996
2425   22.20  Campinas         23          6       1999

In [48]:
print('Dados das menores temperaturas mínimas da história na cidade de {0} no início da primavera\n entre os dias 22 e 31 dos meses de {1}, dados desde {2}'.format('Campinas', mes_escrito,ano_escrito))
print('Fonte:Ciiagro')
print('=' * 40)
print('|{:^3}°)|{:^15}|{:^5}|{:^5}|{:^5}|'.format('Pos.','T. Min(°C)', 'Data','Mês', 'Ano'))
print('=' * 40)



conta = 0
for linha in Tmininicioprimavera.index:
     #nome = tabela_produtos.loc[linha, coluna]
    Tmin = Tmininicioprimavera.loc[linha, "tmin"]
    dia1 = int(Tmininicioprimavera.loc[linha, "Dia_tabela"])   
    mes1 = int(Tmininicioprimavera.loc[linha, "Mes_tabela"])
    ano1 = int(Tmininicioprimavera.loc[linha,'Ano_tabela'] )
    Tmin2 = float(Tmin)
    temperatura1 = round(Tmin2,1)   
    
   # print(temperatura1)
    
    if temperatura1 < 13:
        print('|{:^3}°)|\033[42m{:^15}\033[0m|{:^5}|{:^5}|{:^5}|'.format(conta+1,temperatura1,dia1, mes1,ano1 ))

    else:
        print('|{:^3}°)|{:^15}|{:^5}|{:^5}|{:^5}|'.format(conta+1,temperatura1,dia1, mes1,ano1 ))
        
        pass
    conta = conta +1

print('=' * 40)

Dados das menores temperaturas mínimas da história na cidade de Campinas no início da primavera
 entre os dias 22 e 31 dos meses de Junho, dados desde 1992
Fonte:Ciiagro
========================================
|Pos.°)|  T. Min(°C)   |Data | Mês | Ano |
========================================
| 1 °)|      0.3      | 26  |  6  |1994 |
| 2 °)|      0.6      | 27  |  6  |1994 |
| 3 °)|      2.0      | 28  |  6  |1994 |
| 4 °)|      2.5      | 30  |  6  |2021 |
| 5 °)|      3.7      | 28  |  6  |2011 |
| 6 °)|      4.0      | 29  |  6  |2011 |
| 7 °)|      5.2      | 27  |  6  |2001 |
| 8 °)|      6.0      | 29  |  6  |1994 |
| 9 °)|      6.4      | 28  |  6  |2001 |
|10 °)|      7.9      | 30  |  6  |2011 |
|11 °)|      8.2      | 24  |  6  |2000 |
|12 °)|      8.2      | 23  |  6  |2000 |
|13 °)|      8.2      | 22  |  6  |2000 |

/tmp/ipykernel_17126/3659377644.py:13: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  dia1 = int(Tmininicioprimavera.loc[linha, "Dia_tabela"])
/tmp/ipykernel_17126/3659377644.py:14: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  mes1 = int(Tmininicioprimavera.loc[linha, "Mes_tabela"])
/tmp/ipykernel_17126/3659377644.py:15: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  ano1 = int(Tmininicioprimavera.loc[linha,'Ano_tabela'] )
/tmp/ipykernel_17126/3659377644.py:16: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Tmin2 = float(Tmin)

|14 °)|      8.4      | 23  |  6  |2001 |
|15 °)|      8.6      | 22  |  6  |1993 |
|16 °)|      8.6      | 30  |  6  |1996 |
|17 °)|      8.8      | 24  |  6  |1999 |
|18 °)|      8.9      | 23  |  6  |2009 |
|19 °)|      9.0      | 30  |  6  |1994 |
|20 °)|      9.0      | 22  |  6  |1999 |
|21 °)|      9.0      | 30  |  6  |1999 |
|22 °)|      9.0      | 25  |  6  |1999 |
|23 °)|      9.1      | 22  |  6  |2009 |
|24 °)|      9.2      | 29  |  6  |1996 |
|25 °)|      9.4      | 23  |  6  |1999 |
========================================

In [49]:
teste = Basedados.loc[(Basedados["Ano_tabela"] == 2024)]

In [50]:
teste.sort_values('tmax' , ascending= True).head(40)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
11566  Campinas 2024-07-02            11.33  14.320  17.31              77.32
11530  Campinas 2024-05-27            14.74  17.480  20.22              86.10
11406  Campinas 2024-01-24            17.44  19.265  21.09              90.40
11466  Campinas 2024-03-24            18.41  20.100  21.79              77.64
11533  Campinas 2024-05-30             9.80  16.005  22.21              46.42
11532  Campinas 2024-05-29             9.54  15.925  22.31              79.44
11534  Campinas 2024-05-31            12.22  17.485  22.75              48.02
11565  Campinas 2024-07-01            12.54  18.020  23.50              65.91
11529  Campinas 2024-05-26            14.73  19.280  23.83              67.70
11531  Campinas 2024-05-28            16.53  20.180  23.83              81.40
11471  Campinas 2024-03-29            18.40  21.235  24.07              92.40
11535  Campinas 2024-06-01            12.87  18.610  24.35              41.04
11539  Campinas 2024-06-05            15.88  20.315  24.75              64.92
11429  Campinas 2024-02-16            19.06  21.970  24.88              84.40
11470  Campinas 2024-03-28            19.42  22.195  24.97              77.58
11467  Campinas 2024-03-25            18.73  21.955  25.18              81.20
11492  Campinas 2024-04-19            16.76  21.160  25.56              68.55
11519  Campinas 2024-05-16            18.41  22.295  26.18              68.19
11538  Campinas 2024-06-04            16.04  21.430  26.82              58.25
11465  Campinas 2024-03-23            19.16  23.005  26.85              75.54
11408  Campinas 2024-01-26            17.69  22.390  27.09              66.55
11416  Campinas 2024-02-03            19.77  23.465  27.16              73.32
11411  Campinas 2024-01-29            17.05  22.185  27.32              66.16
11560  Campinas 2024-06-26            14.97  21.180  27.39              62.07
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11469  Campinas 2024-03-27            20.15  23.975  27.80              67.46
11536  Campinas 2024-06-02            11.90  19.905  27.91              36.28
11472  Campinas 2024-03-30            20.51  24.275  28.04              74.10
11556  Campinas 2024-06-22            15.12  21.595  28.07              39.21
11417  Campinas 2024-02-04            19.24  23.750  28.26              73.36
11552  Campinas 2024-06-18            12.08  20.195  28.31              44.07
11540  Campinas 2024-06-06            15.69  22.015  28.34              50.29
11548  Campinas 2024-06-14            12.07  20.205  28.34              40.16
11428  Campinas 2024-02-15            20.77  24.580  28.39              78.90
11409  Campinas 2024-01-27            18.74  23.580  28.42              62.63
11518  Campinas 2024-05-15            18.59  23.555  28.52              56.43
11537  Campinas 2024-06-03            12.91  20.765  28.62              42.32
11553  Campinas 2024-06-19            11.27  20.005  28.74              36.62
11403  Campinas 2024-01-21            20.45  24.600  28.75              78.46

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
11566  88.660  100.0             0.000      0.000  11.33  17.31  Campinas
11530  93.050  100.0            15.750     15.750  14.74  20.22  Campinas
11406  95.200  100.0            22.610     22.610  17.44  21.09  Campinas
11466  88.820  100.0             8.130      8.130  18.41  21.79  Campinas
11533  73.210  100.0             0.000      0.000   9.80  22.21  Campinas
11532  89.720  100.0             0.000      0.000   9.54  22.31  Campinas
11534  71.610   95.2             0.000      0.000  12.22  22.75  Campinas
11565  82.855   99.8             0.510      0.510  12.54  23.50  Campinas
11529  83.850  100.0            18.030     18.030  14.73  23.83  Campinas
11531  90.700  100.0            22.860     22.860  16.53  23.83  Campinas
11471  96.200  100.0            14.220     14.220  18.40  24.07  Campinas
11535  70.220   99.4             0.000      0.000  12.87  24.35  Campinas
11539  81.910   98.9             0.000      0.000  15.88  24.75  Campinas
11429  92.200  100.0             7.366      7.366  19.06  24.88  Campinas
11470  88.790  100.0             5.842      5.842  19.42  24.97  Campinas
11467  90.600  100.0             5.334      5.334  18.73  25.18  Campinas
11492  80.975   93.4             0.000      0.000  16.76  25.56  Campinas
11519  82.345   96.5             0.000      0.000  18.41  26.18  Campinas
11538  78.525   98.8             0.000      0.000  16.04  26.82  Campinas
11465  85.120   94.7             0.000      0.000  19.16  26.85  Campinas
11408  80.375   94.2             0.000      0.000  17.69  27.09  Campinas
11416  85.860   98.4             0.000      0.000  19.77  27.16  Campinas
11411  83.080  100.0             8.890      8.890  17.05  27.32  Campinas
11560  81.035  100.0             0.000      0.000  14.97  27.39  Campinas
11563  75.470  100.0             0.000      0.000  15.10  27.53  Campinas
11562  79.775  100.0             0.000      0.000  15.18  27.78  Campinas
11469  81.180   94.9             0.000      0.000  20.15  27.80  Campinas
11536  67.540   98.8             0.000      0.000  11.90  27.91  Campinas
11472  87.050  100.0             0.000      0.000  20.51  28.04  Campinas
11556  60.005   80.8             0.000      0.000  15.12  28.07  Campinas
11417  86.680  100.0             0.000      0.000  19.24  28.26  Campinas
11552  71.735   99.4             0.000      0.000  12.08  28.31  Campinas
11540  74.145   98.0             0.000      0.000  15.69  28.34  Campinas
11548  66.530   92.9             0.000      0.000  12.07  28.34  Campinas
11428  89.450  100.0             0.760      0.760  20.77  28.39  Campinas
11409  80.015   97.4             0.000      0.000  18.74  28.42  Campinas
11518  76.565   96.7             0.000      0.000  18.59  28.52  Campinas
11537  69.110   95.9             0.000      0.000  12.91  28.62  Campinas
11553  67.960   99.3             0.000      0.000  11.27  28.74  Campinas
11403  89.230  100.0             4.064      4.064  20.45  28.75  Campinas

      Dia_tabela Mes_tabela Ano_tabela

11566          2          7       2024
11530         27          5       2024
11406         24          1       2024
11466         24          3       2024
11533         30          5       2024
11532         29          5       2024
11534         31          5       2024
11565          1          7       2024
11529         26          5       2024
11531         28          5       2024
11471         29          3       2024
11535          1          6       2024
11539          5          6       2024
11429         16          2       2024
11470         28          3       2024
11467         25          3       2024
11492         19          4       2024
11519         16          5       2024
11538          4          6       2024
11465         23          3       2024
11408         26          1       2024
11416          3          2       2024
11411         29          1       2024
11560         26          6       2024
11563         29          6       2024
11562         28          6       2024
11469         27          3       2024
11536          2          6       2024
11472         30          3       2024
11556         22          6       2024
11417          4          2       2024
11552         18          6       2024
11540          6          6       2024
11548         14          6       2024
11428         15          2       2024
11409         27          1       2024
11518         15          5       2024
11537          3          6       2024
11553         19          6       2024
11403         21          1       2024

In [51]:
dois= teste.sort_values('tmax' , ascending= True).head(40)

In [52]:
dois

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
11566  Campinas 2024-07-02            11.33  14.320  17.31              77.32
11530  Campinas 2024-05-27            14.74  17.480  20.22              86.10
11406  Campinas 2024-01-24            17.44  19.265  21.09              90.40
11466  Campinas 2024-03-24            18.41  20.100  21.79              77.64
11533  Campinas 2024-05-30             9.80  16.005  22.21              46.42
11532  Campinas 2024-05-29             9.54  15.925  22.31              79.44
11534  Campinas 2024-05-31            12.22  17.485  22.75              48.02
11565  Campinas 2024-07-01            12.54  18.020  23.50              65.91
11529  Campinas 2024-05-26            14.73  19.280  23.83              67.70
11531  Campinas 2024-05-28            16.53  20.180  23.83              81.40
11471  Campinas 2024-03-29            18.40  21.235  24.07              92.40
11535  Campinas 2024-06-01            12.87  18.610  24.35              41.04
11539  Campinas 2024-06-05            15.88  20.315  24.75              64.92
11429  Campinas 2024-02-16            19.06  21.970  24.88              84.40
11470  Campinas 2024-03-28            19.42  22.195  24.97              77.58
11467  Campinas 2024-03-25            18.73  21.955  25.18              81.20
11492  Campinas 2024-04-19            16.76  21.160  25.56              68.55
11519  Campinas 2024-05-16            18.41  22.295  26.18              68.19
11538  Campinas 2024-06-04            16.04  21.430  26.82              58.25
11465  Campinas 2024-03-23            19.16  23.005  26.85              75.54
11408  Campinas 2024-01-26            17.69  22.390  27.09              66.55
11416  Campinas 2024-02-03            19.77  23.465  27.16              73.32
11411  Campinas 2024-01-29            17.05  22.185  27.32              66.16
11560  Campinas 2024-06-26            14.97  21.180  27.39              62.07
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11469  Campinas 2024-03-27            20.15  23.975  27.80              67.46
11536  Campinas 2024-06-02            11.90  19.905  27.91              36.28
11472  Campinas 2024-03-30            20.51  24.275  28.04              74.10
11556  Campinas 2024-06-22            15.12  21.595  28.07              39.21
11417  Campinas 2024-02-04            19.24  23.750  28.26              73.36
11552  Campinas 2024-06-18            12.08  20.195  28.31              44.07
11540  Campinas 2024-06-06            15.69  22.015  28.34              50.29
11548  Campinas 2024-06-14            12.07  20.205  28.34              40.16
11428  Campinas 2024-02-15            20.77  24.580  28.39              78.90
11409  Campinas 2024-01-27            18.74  23.580  28.42              62.63
11518  Campinas 2024-05-15            18.59  23.555  28.52              56.43
11537  Campinas 2024-06-03            12.91  20.765  28.62              42.32
11553  Campinas 2024-06-19            11.27  20.005  28.74              36.62
11403  Campinas 2024-01-21            20.45  24.600  28.75              78.46

                     Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média Máxima Precipitação (mm)
11566  88.660  100.0             0.000      0.000  11.33  17.31  Campinas
11530  93.050  100.0            15.750     15.750  14.74  20.22  Campinas
11406  95.200  100.0            22.610     22.610  17.44  21.09  Campinas
11466  88.820  100.0             8.130      8.130  18.41  21.79  Campinas
11533  73.210  100.0             0.000      0.000   9.80  22.21  Campinas
11532  89.720  100.0             0.000      0.000   9.54  22.31  Campinas
11534  71.610   95.2             0.000      0.000  12.22  22.75  Campinas
11565  82.855   99.8             0.510      0.510  12.54  23.50  Campinas
11529  83.850  100.0            18.030     18.030  14.73  23.83  Campinas
11531  90.700  100.0            22.860     22.860  16.53  23.83  Campinas
11471  96.200  100.0            14.220     14.220  18.40  24.07  Campinas
11535  70.220   99.4             0.000      0.000  12.87  24.35  Campinas
11539  81.910   98.9             0.000      0.000  15.88  24.75  Campinas
11429  92.200  100.0             7.366      7.366  19.06  24.88  Campinas
11470  88.790  100.0             5.842      5.842  19.42  24.97  Campinas
11467  90.600  100.0             5.334      5.334  18.73  25.18  Campinas
11492  80.975   93.4             0.000      0.000  16.76  25.56  Campinas
11519  82.345   96.5             0.000      0.000  18.41  26.18  Campinas
11538  78.525   98.8             0.000      0.000  16.04  26.82  Campinas
11465  85.120   94.7             0.000      0.000  19.16  26.85  Campinas
11408  80.375   94.2             0.000      0.000  17.69  27.09  Campinas
11416  85.860   98.4             0.000      0.000  19.77  27.16  Campinas
11411  83.080  100.0             8.890      8.890  17.05  27.32  Campinas
11560  81.035  100.0             0.000      0.000  14.97  27.39  Campinas
11563  75.470  100.0             0.000      0.000  15.10  27.53  Campinas
11562  79.775  100.0             0.000      0.000  15.18  27.78  Campinas
11469  81.180   94.9             0.000      0.000  20.15  27.80  Campinas
11536  67.540   98.8             0.000      0.000  11.90  27.91  Campinas
11472  87.050  100.0             0.000      0.000  20.51  28.04  Campinas
11556  60.005   80.8             0.000      0.000  15.12  28.07  Campinas
11417  86.680  100.0             0.000      0.000  19.24  28.26  Campinas
11552  71.735   99.4             0.000      0.000  12.08  28.31  Campinas
11540  74.145   98.0             0.000      0.000  15.69  28.34  Campinas
11548  66.530   92.9             0.000      0.000  12.07  28.34  Campinas
11428  89.450  100.0             0.760      0.760  20.77  28.39  Campinas
11409  80.015   97.4             0.000      0.000  18.74  28.42  Campinas
11518  76.565   96.7             0.000      0.000  18.59  28.52  Campinas
11537  69.110   95.9             0.000      0.000  12.91  28.62  Campinas
11553  67.960   99.3             0.000      0.000  11.27  28.74  Campinas
11403  89.230  100.0             4.064      4.064  20.45  28.75  Campinas

      Dia_tabela Mes_tabela Ano_tabela

11566          2          7       2024
11530         27          5       2024
11406         24          1       2024
11466         24          3       2024
11533         30          5       2024
11532         29          5       2024
11534         31          5       2024
11565          1          7       2024
11529         26          5       2024
11531         28          5       2024
11471         29          3       2024
11535          1          6       2024
11539          5          6       2024
11429         16          2       2024
11470         28          3       2024
11467         25          3       2024
11492         19          4       2024
11519         16          5       2024
11538          4          6       2024
11465         23          3       2024
11408         26          1       2024
11416          3          2       2024
11411         29          1       2024
11560         26          6       2024
11563         29          6       2024
11562         28          6       2024
11469         27          3       2024
11536          2          6       2024
11472         30          3       2024
11556         22          6       2024
11417          4          2       2024
11552         18          6       2024
11540          6          6       2024
11548         14          6       2024
11428         15          2       2024
11409         27          1       2024
11518         15          5       2024
11537          3          6       2024
11553         19          6       2024
11403         21          1       2024

In [53]:
dois2 = dois[['cidade','tmax','Dia_tabela', 'Mes_tabela', 'Ano_tabela' ]]

In [54]:
print('Menores temperaturas máximas deste ano, segundo dados do Ciiagro')
dois2

Menores temperaturas máximas deste ano, segundo dados do Ciiagro

         cidade   tmax Dia_tabela Mes_tabela Ano_tabela

11566  Campinas  17.31          2          7       2024
11530  Campinas  20.22         27          5       2024
11406  Campinas  21.09         24          1       2024
11466  Campinas  21.79         24          3       2024
11533  Campinas  22.21         30          5       2024
11532  Campinas  22.31         29          5       2024
11534  Campinas  22.75         31          5       2024
11565  Campinas  23.50          1          7       2024
11529  Campinas  23.83         26          5       2024
11531  Campinas  23.83         28          5       2024
11471  Campinas  24.07         29          3       2024
11535  Campinas  24.35          1          6       2024
11539  Campinas  24.75          5          6       2024
11429  Campinas  24.88         16          2       2024
11470  Campinas  24.97         28          3       2024
11467  Campinas  25.18         25          3       2024
11492  Campinas  25.56         19          4       2024
11519  Campinas  26.18         16          5       2024
11538  Campinas  26.82          4          6       2024
11465  Campinas  26.85         23          3       2024
11408  Campinas  27.09         26          1       2024
11416  Campinas  27.16          3          2       2024
11411  Campinas  27.32         29          1       2024
11560  Campinas  27.39         26          6       2024
11563  Campinas  27.53         29          6       2024
11562  Campinas  27.78         28          6       2024
11469  Campinas  27.80         27          3       2024
11536  Campinas  27.91          2          6       2024
11472  Campinas  28.04         30          3       2024
11556  Campinas  28.07         22          6       2024
11417  Campinas  28.26          4          2       2024
11552  Campinas  28.31         18          6       2024
11540  Campinas  28.34          6          6       2024
11548  Campinas  28.34         14          6       2024
11428  Campinas  28.39         15          2       2024
11409  Campinas  28.42         27          1       2024
11518  Campinas  28.52         15          5       2024
11537  Campinas  28.62          3          6       2024
11553  Campinas  28.74         19          6       2024
11403  Campinas  28.75         21          1       2024

In [55]:
dois2['Dia_Correto'] = dois2['Dia_tabela'] - 1

/tmp/ipykernel_17126/1404598843.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dois2['Dia_Correto'] = dois2['Dia_tabela'] - 1

In [56]:
dois2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 11566 to 11403
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (cidade, )       40 non-null     object
 1   (tmax, )         40 non-null     float64
 2   (Dia_tabela, )   40 non-null     int32
 3   (Mes_tabela, )   40 non-null     int32
 4   (Ano_tabela, )   40 non-null     int32
 5   (Dia_Correto, )  40 non-null     int32
dtypes: float64(1), int32(4), object(1)
memory usage: 1.6+ KB

In [57]:
print('Menores temperaturas máximas deste ano, segundo dados do Ciiagro')
dois2

Menores temperaturas máximas deste ano, segundo dados do Ciiagro

         cidade   tmax Dia_tabela Mes_tabela Ano_tabela Dia_Correto

11566  Campinas  17.31          2          7       2024           1
11530  Campinas  20.22         27          5       2024          26
11406  Campinas  21.09         24          1       2024          23
11466  Campinas  21.79         24          3       2024          23
11533  Campinas  22.21         30          5       2024          29
11532  Campinas  22.31         29          5       2024          28
11534  Campinas  22.75         31          5       2024          30
11565  Campinas  23.50          1          7       2024           0
11529  Campinas  23.83         26          5       2024          25
11531  Campinas  23.83         28          5       2024          27
11471  Campinas  24.07         29          3       2024          28
11535  Campinas  24.35          1          6       2024           0
11539  Campinas  24.75          5          6       2024           4
11429  Campinas  24.88         16          2       2024          15
11470  Campinas  24.97         28          3       2024          27
11467  Campinas  25.18         25          3       2024          24
11492  Campinas  25.56         19          4       2024          18
11519  Campinas  26.18         16          5       2024          15
11538  Campinas  26.82          4          6       2024           3
11465  Campinas  26.85         23          3       2024          22
11408  Campinas  27.09         26          1       2024          25
11416  Campinas  27.16          3          2       2024           2
11411  Campinas  27.32         29          1       2024          28
11560  Campinas  27.39         26          6       2024          25
11563  Campinas  27.53         29          6       2024          28
11562  Campinas  27.78         28          6       2024          27
11469  Campinas  27.80         27          3       2024          26
11536  Campinas  27.91          2          6       2024           1
11472  Campinas  28.04         30          3       2024          29
11556  Campinas  28.07         22          6       2024          21
11417  Campinas  28.26          4          2       2024           3
11552  Campinas  28.31         18          6       2024          17
11540  Campinas  28.34          6          6       2024           5
11548  Campinas  28.34         14          6       2024          13
11428  Campinas  28.39         15          2       2024          14
11409  Campinas  28.42         27          1       2024          26
11518  Campinas  28.52         15          5       2024          14
11537  Campinas  28.62          3          6       2024           2
11553  Campinas  28.74         19          6       2024          18
11403  Campinas  28.75         21          1       2024          20

In [60]:
dois2 = dois2[['cidade','tmax','Dia_Correto', 'Mes_tabela', 'Ano_tabela' ]]

In [61]:
print('Menores temperaturas máximas deste ano em {}, segundo dados do Ciiagro'.format(dois2['cidade'][11403]))
dois2

Menores temperaturas máximas deste ano em Campinas, segundo dados do Ciiagro

         cidade   tmax Dia_Correto Mes_tabela Ano_tabela

11566  Campinas  17.31           1          7       2024
11530  Campinas  20.22          26          5       2024
11406  Campinas  21.09          23          1       2024
11466  Campinas  21.79          23          3       2024
11533  Campinas  22.21          29          5       2024
11532  Campinas  22.31          28          5       2024
11534  Campinas  22.75          30          5       2024
11565  Campinas  23.50           0          7       2024
11529  Campinas  23.83          25          5       2024
11531  Campinas  23.83          27          5       2024
11471  Campinas  24.07          28          3       2024
11535  Campinas  24.35           0          6       2024
11539  Campinas  24.75           4          6       2024
11429  Campinas  24.88          15          2       2024
11470  Campinas  24.97          27          3       2024
11467  Campinas  25.18          24          3       2024
11492  Campinas  25.56          18          4       2024
11519  Campinas  26.18          15          5       2024
11538  Campinas  26.82           3          6       2024
11465  Campinas  26.85          22          3       2024
11408  Campinas  27.09          25          1       2024
11416  Campinas  27.16           2          2       2024
11411  Campinas  27.32          28          1       2024
11560  Campinas  27.39          25          6       2024
11563  Campinas  27.53          28          6       2024
11562  Campinas  27.78          27          6       2024
11469  Campinas  27.80          26          3       2024
11536  Campinas  27.91           1          6       2024
11472  Campinas  28.04          29          3       2024
11556  Campinas  28.07          21          6       2024
11417  Campinas  28.26           3          2       2024
11552  Campinas  28.31          17          6       2024
11540  Campinas  28.34           5          6       2024
11548  Campinas  28.34          13          6       2024
11428  Campinas  28.39          14          2       2024
11409  Campinas  28.42          26          1       2024
11518  Campinas  28.52          14          5       2024
11537  Campinas  28.62           2          6       2024
11553  Campinas  28.74          18          6       2024
11403  Campinas  28.75          20          1       2024

In [62]:
teste.tail(30)

          Local       Data Temperatura (°C)                Umidade do ar (mm)  \
          Local       Data           Mínima   Média Máxima             Mínima
11537  Campinas 2024-06-03            12.91  20.765  28.62              42.32
11538  Campinas 2024-06-04            16.04  21.430  26.82              58.25
11539  Campinas 2024-06-05            15.88  20.315  24.75              64.92
11540  Campinas 2024-06-06            15.69  22.015  28.34              50.29
11541  Campinas 2024-06-07            14.59  22.010  29.43              43.23
11542  Campinas 2024-06-08            14.94  22.345  29.75              44.76
11543  Campinas 2024-06-09            14.57  21.880  29.19              45.63
11544  Campinas 2024-06-10            13.86  21.465  29.07              45.80
11545  Campinas 2024-06-11            14.27  21.865  29.46              46.97
11546  Campinas 2024-06-12            15.64  22.700  29.76              44.13
11547  Campinas 2024-06-13            13.87  22.090  30.31              35.13
11548  Campinas 2024-06-14            12.07  20.205  28.34              40.16
11549  Campinas 2024-06-15            15.36  22.225  29.09              36.33
11550  Campinas 2024-06-16            15.06  22.435  29.81              43.61
11551  Campinas 2024-06-17            14.63  22.085  29.54              44.42
11552  Campinas 2024-06-18            12.08  20.195  28.31              44.07
11553  Campinas 2024-06-19            11.27  20.005  28.74              36.62
11554  Campinas 2024-06-20            12.12  20.730  29.34              37.47
11555  Campinas 2024-06-21            14.08  22.245  30.41              30.50
11556  Campinas 2024-06-22            15.12  21.595  28.07              39.21
11557  Campinas 2024-06-23            14.15  21.855  29.56              39.17
11558  Campinas 2024-06-24            14.39  22.215  30.04              42.45
11559  Campinas 2024-06-25            14.92  22.780  30.64              43.07
11560  Campinas 2024-06-26            14.97  21.180  27.39              62.07
11561  Campinas 2024-06-27            15.00  22.875  30.75              45.30
11562  Campinas 2024-06-28            15.18  21.480  27.78              59.55
11563  Campinas 2024-06-29            15.10  21.315  27.53              50.94
11564  Campinas 2024-06-30            16.25  22.780  29.31              43.23
11565  Campinas 2024-07-01            12.54  18.020  23.50              65.91
11566  Campinas 2024-07-02            11.33  14.320  17.31              77.32

                      Precipitação (mm) chuva (mm)   tmin   tmax    cidade  \
        Média  Máxima Precipitação (mm)
11537  69.110   95.90              0.00       0.00  12.91  28.62  Campinas
11538  78.525   98.80              0.00       0.00  16.04  26.82  Campinas
11539  81.910   98.90              0.00       0.00  15.88  24.75  Campinas
11540  74.145   98.00              0.00       0.00  15.69  28.34  Campinas
11541  70.165   97.10              0.00       0.00  14.59  29.43  Campinas
11542  68.730   92.70              0.00       0.00  14.94  29.75  Campinas
11543  71.815   98.00              0.00       0.00  14.57  29.19  Campinas
11544  72.900  100.00              0.00       0.00  13.86  29.07  Campinas
11545  73.485  100.00              0.00       0.00  14.27  29.46  Campinas
11546  70.265   96.40              0.00       0.00  15.64  29.76  Campinas
11547  62.915   90.70              0.00       0.00  13.87  30.31  Campinas
11548  66.530   92.90              0.00       0.00  12.07  28.34  Campinas
11549  65.565   94.80              0.00       0.00  15.36  29.09  Campinas
11550  70.305   97.00              0.00       0.00  15.06  29.81  Campinas
11551  69.510   94.60              0.00       0.00  14.63  29.54  Campinas
11552  71.735   99.40              0.00       0.00  12.08  28.31  Campinas
11553  67.960   99.30              0.00       0.00  11.27  28.74  Campinas
11554  66.835   96.20              0.00       0.00  12.12  29.34  Campinas
11555  55.235   79.97              0.00       0.00  14.08  30.41  Campinas
11556  60.005   80.80              0.00       0.00  15.12  28.07  Campinas
11557  67.085   95.00              0.00       0.00  14.15  29.56  Campinas
11558  69.425   96.40              0.00       0.00  14.39  30.04  Campinas
11559  69.385   95.70              0.00       0.00  14.92  30.64  Campinas
11560  81.035  100.00              0.00       0.00  14.97  27.39  Campinas
11561  72.650  100.00              0.00       0.00  15.00  30.75  Campinas
11562  79.775  100.00              0.00       0.00  15.18  27.78  Campinas
11563  75.470  100.00              0.00       0.00  15.10  27.53  Campinas
11564  70.915   98.60              0.00       0.00  16.25  29.31  Campinas
11565  82.855   99.80              0.51       0.51  12.54  23.50  Campinas
11566  88.660  100.00              0.00       0.00  11.33  17.31  Campinas

      Dia_tabela Mes_tabela Ano_tabela

11537          3          6       2024
11538          4          6       2024
11539          5          6       2024
11540          6          6       2024
11541          7          6       2024
11542          8          6       2024
11543          9          6       2024
11544         10          6       2024
11545         11          6       2024
11546         12          6       2024
11547         13          6       2024
11548         14          6       2024
11549         15          6       2024
11550         16          6       2024
11551         17          6       2024
11552         18          6       2024
11553         19          6       2024
11554         20          6       2024
11555         21          6       2024
11556         22          6       2024
11557         23          6       2024
11558         24          6       2024
11559         25          6       2024
11560         26          6       2024
11561         27          6       2024
11562         28          6       2024
11563         29          6       2024
11564         30          6       2024
11565          1          7       2024
11566          2          7       2024

In [63]:
temindois=teste.sort_values('tmin' , ascending= True).head(14)

In [64]:
temindois = temindois[['cidade','tmin','Dia_tabela', 'Mes_tabela', 'Ano_tabela' ]]

In [65]:
print('menores temperaturas mínimas de 2023 em Campinas, fonte Ciiagro')
temindois.round(2)

menores temperaturas mínimas de 2023 em Campinas, fonte Ciiagro

         cidade   tmin Dia_tabela Mes_tabela Ano_tabela

11532  Campinas   9.54         29          5       2024
11533  Campinas   9.80         30          5       2024
11553  Campinas  11.27         19          6       2024
11566  Campinas  11.33          2          7       2024
11536  Campinas  11.90          2          6       2024
11548  Campinas  12.07         14          6       2024
11552  Campinas  12.08         18          6       2024
11554  Campinas  12.12         20          6       2024
11534  Campinas  12.22         31          5       2024
11565  Campinas  12.54          1          7       2024
11535  Campinas  12.87          1          6       2024
11537  Campinas  12.91          3          6       2024
11544  Campinas  13.86         10          6       2024
11547  Campinas  13.87         13          6       2024